# 是否启用插件
# Whether to enable the plugin
enable-plugin: false

# 语言，默认简体中文
# 当前支持设置为：zh_hans / zh_hant / en_us / ja_jp
# Language, default is zh_hans (Simplified Chinese)
# Now support: zh_hans / zh_hant / en_us / ja_jp
language: zh_hans

# 起始uid（如起始uid为10000则第一个注册的玩家为10001，在后续修改本配置将会让新玩家的UID从你配置的UID开始）
# Starting UID (If the starting UID is 10000, the first registered player will be 10001, and subsequent changes to this configuration will make the UID of the new player start from your configuration)
starting_uid: 1000000

# 是否显示查询耗时
# Whether to display query time
show_query_time: false

# MySQL数据库设置
# MySQL database settings
mysql:
  host: localhost
  port: 3306
  database: meow_uid
  username: meow_uid
  password: password

# 请确保接入跨服的所有服务器的配置文件均相同！！
# Please ensure that the configuration files of all servers are the same!!