name: MeowUID
main: com.meow.meowuid.MeowUID
version: 1.1
api-version: 1.16
description: A plugin to assign unique UIDs to players and sync across multiple servers using MySQL.
softdepend: [PlaceholderAPI]

commands:
  muid:
    description: Manage and query player UIDs.
    usage: /muid <find|reload>
    permission: meowuid.admin
    permission-message: "§cYou do not have permission to use this command."
    
permissions:
  meowuid.admin:
    description: Allows access to all /muid commands.
    default: op
